variables:
  DOCKER_DRIVER: overlay2

image: node:10

stages:
  - test
  - build
  - deploy
  - publish

test-diff-patch-sync:
  stage: test
  script:
      - npm i
      - npm run coverage

build-diff-patch-sync:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
      - node_modules/
    name: "Build diff-patch-sync"
    expire_in: 1 week
    when: on_success

publish-diff-patch-sync:
  stage: publish
  script:
#    - echo '//registry.npmjs.org/:_authToken=$NPM_TOKEN' > .npmrc
#    - echo '//gitlab.com/api/v4/projects/diff-patch-sync/packages/npm/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm config set //gitlab.com/api/v4/projects/diff-patch-sync/packages/npm/:_authToken=$NPM_TOKEN
    - npm config
    - npm publish
  needs:
    - build-diff-patch-sync
  dependencies:
    - build-diff-patch-sync
#  only:
#    refs:
#      - triggers
#      - tags

